//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NHSEntities : DbContext
    {
        public NHSEntities()
            : base("name=NHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvoidabilityScore> AvoidabilityScores { get; set; }
        public virtual DbSet<CarePhase> CarePhases { get; set; }
        public virtual DbSet<CareRating> CareRatings { get; set; }
        public virtual DbSet<CoronerReferralReason> CoronerReferralReasons { get; set; }
        public virtual DbSet<FeedBack> FeedBacks { get; set; }
        public virtual DbSet<MedicalExaminer> MedicalExaminers { get; set; }
        public virtual DbSet<MedicalExaminerDecision> MedicalExaminerDecisions { get; set; }
        public virtual DbSet<MedicalExaminerReview> MedicalExaminerReviews { get; set; }
        public virtual DbSet<MortalitySurveillance> MortalitySurveillances { get; set; }
        public virtual DbSet<OtherReferral> OtherReferrals { get; set; }
        public virtual DbSet<PatientMap> PatientMaps { get; set; }
        public virtual DbSet<ResponsePT> ResponsePTs { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SJRFormInitial> SJRFormInitials { get; set; }
        public virtual DbSet<SJRFormProblemType> SJRFormProblemTypes { get; set; }
        public virtual DbSet<SJROutcomes> SJROutcomes1 { get; set; }
        public virtual DbSet<SJRReview> SJRReviews { get; set; }
        public virtual DbSet<SJRReviewSpeciality> SJRReviewSpecialities { get; set; }
        public virtual DbSet<UserInRole> UserInRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSession> UserSessions { get; set; }
        public virtual DbSet<DischargeConsultant> DischargeConsultants { get; set; }
        public virtual DbSet<PatientDetail> PatientDetails { get; set; }
    }
}
