//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NHSEntities : DbContext
    {
        public NHSEntities()
            : base("name=NHSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvoidabilityScore> AvoidabilityScore { get; set; }
        public virtual DbSet<CarePhase> CarePhase { get; set; }
        public virtual DbSet<CareRating> CareRating { get; set; }
        public virtual DbSet<ClinicalCoding> ClinicalCoding { get; set; }
        public virtual DbSet<CoronerReferralReason> CoronerReferralReason { get; set; }
        public virtual DbSet<DischargeConsultant> DischargeConsultant { get; set; }
        public virtual DbSet<FeedBack> FeedBack { get; set; }
        public virtual DbSet<MedicalExaminer> MedicalExaminer { get; set; }
        public virtual DbSet<MedicalExaminerDecision> MedicalExaminerDecision { get; set; }
        public virtual DbSet<MedicalExaminerReview> MedicalExaminerReview { get; set; }
        public virtual DbSet<MortalitySurveillance> MortalitySurveillance { get; set; }
        public virtual DbSet<OtherReferral> OtherReferral { get; set; }
        public virtual DbSet<PatientDetails> PatientDetails { get; set; }
        public virtual DbSet<PatientMap> PatientMap { get; set; }
        public virtual DbSet<ResponsePT> ResponsePT { get; set; }
        public virtual DbSet<ReviewStatus> ReviewStatus { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<SJRFormInitial> SJRFormInitial { get; set; }
        public virtual DbSet<SJRFormProblemType> SJRFormProblemType { get; set; }
        public virtual DbSet<SJROutcomes> SJROutcomes { get; set; }
        public virtual DbSet<SJRReview> SJRReview { get; set; }
        public virtual DbSet<SJRReviewSpeciality> SJRReviewSpeciality { get; set; }
        public virtual DbSet<UserInRoles> UserInRoles { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserSession> UserSession { get; set; }
        public virtual DbSet<DataManagement> DataManagement { get; set; }
    }
}
