//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetail
    {
        public int PatientId { get; set; }
        public string PatientName { get; set; }
        public string MRN { get; set; }
        public Nullable<bool> Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DateofAdmission { get; set; }
        public string DischargeWard { get; set; }
        public Nullable<int> DischargeConsultantCode { get; set; }
        public string EmergencyAdmission { get; set; }
        public Nullable<System.DateTime> TimeofAdmission { get; set; }
        public Nullable<System.DateTime> DateofDeath { get; set; }
        public Nullable<System.DateTime> TimeofDeath { get; set; }
        public string PrimaryDiagnosis { get; set; }
        public Nullable<bool> CodingIssueIdentified { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual DischargeConsultant DischargeConsultant { get; set; }
    }
}
