//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatientDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PatientDetails()
        {
            this.ClinicalCoding = new HashSet<ClinicalCoding>();
            this.FeedBack = new HashSet<FeedBack>();
            this.MedicalExaminerReview = new HashSet<MedicalExaminerReview>();
            this.MortalitySurveillance = new HashSet<MortalitySurveillance>();
            this.OtherReferral = new HashSet<OtherReferral>();
            this.ReviewStatus = new HashSet<ReviewStatus>();
            this.SJRFormInitial = new HashSet<SJRFormInitial>();
            this.SJRFormProblemType = new HashSet<SJRFormProblemType>();
            this.SJROutcomes = new HashSet<SJROutcomes>();
            this.SJRReview = new HashSet<SJRReview>();
            this.MedicalExaminerDecision = new HashSet<MedicalExaminerDecision>();
        }
    
        public int PatientId { get; set; }
        public Nullable<int> SpellNumber { get; set; }
        public string PatientName { get; set; }
        public Nullable<int> NHSNumber { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> DateofAdmission { get; set; }
        public Nullable<System.TimeSpan> TimeofAdmission { get; set; }
        public string DischargeWard { get; set; }
        public Nullable<System.DateTime> DateofDeath { get; set; }
        public Nullable<System.TimeSpan> TimeofDeath { get; set; }
        public string WardofDeath { get; set; }
        public string DischargeConsultantCode { get; set; }
        public string DischargeConsutantName { get; set; }
        public string DischargeSpecialtyCode { get; set; }
        public string DischargeSpeciality { get; set; }
        public string Caregroup { get; set; }
        public string AdmissionType { get; set; }
        public string PrimaryDiagnosis { get; set; }
        public string PrimaryProcedure { get; set; }
        public Nullable<int> ComorbiditiesCount { get; set; }
        public string SHMIGroup { get; set; }
        public Nullable<bool> CodingIssueIdentified { get; set; }
        public string Comments { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClinicalCoding> ClinicalCoding { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FeedBack> FeedBack { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalExaminerReview> MedicalExaminerReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MortalitySurveillance> MortalitySurveillance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OtherReferral> OtherReferral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReviewStatus> ReviewStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SJRFormInitial> SJRFormInitial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SJRFormProblemType> SJRFormProblemType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SJROutcomes> SJROutcomes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SJRReview> SJRReview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedicalExaminerDecision> MedicalExaminerDecision { get; set; }
    }
}
