//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReviewStatus
    {
        public int ReviewStatusId { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string Spellnumber { get; set; }
        public Nullable<int> METriage { get; set; }
        public Nullable<int> SJR1 { get; set; }
        public Nullable<int> SJR2 { get; set; }
        public Nullable<int> SJRoutcome { get; set; }
        public string MortalityReview { get; set; }
        public string CodingReview { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual PatientDetails PatientDetails { get; set; }
        public virtual ReviewStatus ReviewStatus1 { get; set; }
        public virtual ReviewStatus ReviewStatus2 { get; set; }
    }
}
