//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SJRFormProblemType
    {
        public int SJRFormProblemType_ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<int> AssessmentResponseID { get; set; }
        public Nullable<int> AssessmentCarePhaseID { get; set; }
        public Nullable<int> MedicationResponseID { get; set; }
        public Nullable<int> MedicationCarePhaseID { get; set; }
        public Nullable<int> TreatmentResponseID { get; set; }
        public Nullable<int> TreatmentCarePhaseID { get; set; }
        public Nullable<int> InfectionResponseID { get; set; }
        public Nullable<int> InfectionCarePhaseID { get; set; }
        public Nullable<int> ProcedureResponseID { get; set; }
        public Nullable<int> ProcedureCarePhaseID { get; set; }
        public Nullable<int> MonitoringResponseID { get; set; }
        public Nullable<int> ResuscitationResponseID { get; set; }
        public Nullable<int> OthertypeResponseID { get; set; }
        public Nullable<int> OthertypeCarePhaseID { get; set; }
        public Nullable<int> AvoidabilityScoreID { get; set; }
        public string Comments { get; set; }
        public Nullable<int> Stage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual AvoidabilityScore AvoidabilityScore { get; set; }
        public virtual CarePhase CarePhase { get; set; }
        public virtual CarePhase CarePhase1 { get; set; }
        public virtual CarePhase CarePhase2 { get; set; }
        public virtual CarePhase CarePhase3 { get; set; }
        public virtual CarePhase CarePhase4 { get; set; }
        public virtual CarePhase CarePhase5 { get; set; }
        public virtual PatientMap PatientMap { get; set; }
        public virtual ResponsePT ResponsePT { get; set; }
        public virtual ResponsePT ResponsePT1 { get; set; }
        public virtual ResponsePT ResponsePT2 { get; set; }
        public virtual ResponsePT ResponsePT3 { get; set; }
        public virtual ResponsePT ResponsePT4 { get; set; }
        public virtual ResponsePT ResponsePT5 { get; set; }
        public virtual ResponsePT ResponsePT6 { get; set; }
        public virtual ResponsePT ResponsePT7 { get; set; }
    }
}
