//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SJRFormInitial
    {
        public int SJRFormInitial_ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public string InitialManagement { get; set; }
        public Nullable<int> InitialManagementCareRatingID { get; set; }
        public string OngoingCare { get; set; }
        public Nullable<int> OngoingCareRatingID { get; set; }
        public string CareDuringProcedure { get; set; }
        public Nullable<int> CareDuringProcedureCareRatingID { get; set; }
        public string EndLifeCare { get; set; }
        public Nullable<int> EndLifeCareRatingID { get; set; }
        public string OverAllAssessment { get; set; }
        public Nullable<int> OverAllAssessmentCareRatingID { get; set; }
        public Nullable<int> Stage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual CareRating CareRating { get; set; }
        public virtual CareRating CareRating1 { get; set; }
        public virtual CareRating CareRating2 { get; set; }
        public virtual CareRating CareRating3 { get; set; }
        public virtual CareRating CareRating4 { get; set; }
        public virtual PatientMap PatientMap { get; set; }
    }
}
