//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SJRReview
    {
        public int SJRReview_ID { get; set; }
        public Nullable<int> PatientID { get; set; }
        public Nullable<bool> PaediatricPatient { get; set; }
        public Nullable<bool> LearningDisabilityPatient { get; set; }
        public Nullable<bool> MentalillnessPatient { get; set; }
        public Nullable<bool> ElectiveAdmission { get; set; }
        public Nullable<bool> NoKConcernsDeath { get; set; }
        public Nullable<bool> OtherConcern { get; set; }
        public Nullable<bool> FullSJRRequired { get; set; }
        public Nullable<int> SJRReviewSpecialityID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual PatientMap PatientMap { get; set; }
        public virtual SJRReviewSpeciality SJRReviewSpeciality { get; set; }
    }
}
